### SUBSCRIPTION

# @no-log
POST http://localhost:3500/subscription
Content-Type: application/json

{
  "title": "Reform",
  "description": "Reform news",
  "link": "https://reform.news/feed"
}

###

# @no-log
GET http://localhost:3500/subscription
Accept: application/json

###

# @no-log
GET http://localhost:3500/subscription/68232604546d3f3f3f491594
Accept: application/json

###

# @no-log
PATCH http://localhost:3500/subscription/681e5f2c902047b638c6a314
Content-Type: application/json

{
  "description": "Habaaaa JavaScript"
}

###


# @no-log
DELETE http://localhost:3500/subscription/6824d5a05f08abd8146c09bf
Content-Type: application/json

###
