### SUBSCRIPTION

# @no-log
POST http://localhost:3500/subscription
Content-Type: application/json

{
  "title": "Reform",
  "description": "Reform news",
  "link": "https://reform.news/feed"
}

###

# @no-log
GET http://localhost:3500/subscription
Accept: application/json

###

# @no-log
GET http://localhost:3500/subscription/68232353faa64fae67387185
Accept: application/json

###

# @no-log
PATCH http://localhost:3500/subscription/681e5f2c902047b638c6a314
Content-Type: application/json

{
  "description": "Habaaaa JavaScript"
}

###


# @no-log
DELETE http://localhost:3500/subscription/681e5efd902047b638c6a30b
Content-Type: application/json

###
